// <auto-generated />
using Formula1Backend.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formula1Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711211813_AddSeedToEscuderia")]
    partial class AddSeedToEscuderia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Formula1Backend.Models.Entities.Escuderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AñoFundacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Escuderias");
                });

            modelBuilder.Entity("Formula1Backend.Models.Entities.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscuderiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EscuderiaId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("Formula1Backend.Models.Entities.Pista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MejorPilotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MejorPilotoId");

                    b.ToTable("Pistas");
                });

            modelBuilder.Entity("Formula1Backend.Models.Entities.Piloto", b =>
                {
                    b.HasOne("Formula1Backend.Models.Entities.Escuderia", "Escuderia")
                        .WithMany("Pilotos")
                        .HasForeignKey("EscuderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuderia");
                });

            modelBuilder.Entity("Formula1Backend.Models.Entities.Pista", b =>
                {
                    b.HasOne("Formula1Backend.Models.Entities.Piloto", "MejorPiloto")
                        .WithMany()
                        .HasForeignKey("MejorPilotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MejorPiloto");
                });

            modelBuilder.Entity("Formula1Backend.Models.Entities.Escuderia", b =>
                {
                    b.Navigation("Pilotos");
                });
#pragma warning restore 612, 618
        }
    }
}
